// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

package gauge_messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type APIMessage_APIMessageType int32

const (
	APIMessage_GetProjectRootRequest            APIMessage_APIMessageType = 0
	APIMessage_GetProjectRootResponse           APIMessage_APIMessageType = 1
	APIMessage_GetInstallationRootRequest       APIMessage_APIMessageType = 2
	APIMessage_GetInstallationRootResponse      APIMessage_APIMessageType = 3
	APIMessage_GetAllStepsRequest               APIMessage_APIMessageType = 4
	APIMessage_GetAllStepResponse               APIMessage_APIMessageType = 5
	APIMessage_SpecsRequest                     APIMessage_APIMessageType = 6
	APIMessage_SpecsResponse                    APIMessage_APIMessageType = 7
	APIMessage_GetStepValueRequest              APIMessage_APIMessageType = 8
	APIMessage_GetStepValueResponse             APIMessage_APIMessageType = 9
	APIMessage_GetLanguagePluginLibPathRequest  APIMessage_APIMessageType = 10
	APIMessage_GetLanguagePluginLibPathResponse APIMessage_APIMessageType = 11
	APIMessage_ErrorResponse                    APIMessage_APIMessageType = 12
	APIMessage_GetAllConceptsRequest            APIMessage_APIMessageType = 13
	APIMessage_GetAllConceptsResponse           APIMessage_APIMessageType = 14
	APIMessage_PerformRefactoringRequest        APIMessage_APIMessageType = 15
	APIMessage_PerformRefactoringResponse       APIMessage_APIMessageType = 16
	APIMessage_ExtractConceptRequest            APIMessage_APIMessageType = 17
	APIMessage_ExtractConceptResponse           APIMessage_APIMessageType = 18
	APIMessage_FormatSpecsRequest               APIMessage_APIMessageType = 19
	APIMessage_FormatSpecsResponse              APIMessage_APIMessageType = 20
	APIMessage_UnsupportedApiMessageResponse    APIMessage_APIMessageType = 21
)

var APIMessage_APIMessageType_name = map[int32]string{
	0:  "GetProjectRootRequest",
	1:  "GetProjectRootResponse",
	2:  "GetInstallationRootRequest",
	3:  "GetInstallationRootResponse",
	4:  "GetAllStepsRequest",
	5:  "GetAllStepResponse",
	6:  "SpecsRequest",
	7:  "SpecsResponse",
	8:  "GetStepValueRequest",
	9:  "GetStepValueResponse",
	10: "GetLanguagePluginLibPathRequest",
	11: "GetLanguagePluginLibPathResponse",
	12: "ErrorResponse",
	13: "GetAllConceptsRequest",
	14: "GetAllConceptsResponse",
	15: "PerformRefactoringRequest",
	16: "PerformRefactoringResponse",
	17: "ExtractConceptRequest",
	18: "ExtractConceptResponse",
	19: "FormatSpecsRequest",
	20: "FormatSpecsResponse",
	21: "UnsupportedApiMessageResponse",
}
var APIMessage_APIMessageType_value = map[string]int32{
	"GetProjectRootRequest":            0,
	"GetProjectRootResponse":           1,
	"GetInstallationRootRequest":       2,
	"GetInstallationRootResponse":      3,
	"GetAllStepsRequest":               4,
	"GetAllStepResponse":               5,
	"SpecsRequest":                     6,
	"SpecsResponse":                    7,
	"GetStepValueRequest":              8,
	"GetStepValueResponse":             9,
	"GetLanguagePluginLibPathRequest":  10,
	"GetLanguagePluginLibPathResponse": 11,
	"ErrorResponse":                    12,
	"GetAllConceptsRequest":            13,
	"GetAllConceptsResponse":           14,
	"PerformRefactoringRequest":        15,
	"PerformRefactoringResponse":       16,
	"ExtractConceptRequest":            17,
	"ExtractConceptResponse":           18,
	"FormatSpecsRequest":               19,
	"FormatSpecsResponse":              20,
	"UnsupportedApiMessageResponse":    21,
}

func (x APIMessage_APIMessageType) String() string {
	return proto.EnumName(APIMessage_APIMessageType_name, int32(x))
}
func (APIMessage_APIMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{27, 0}
}

// / Request to get the Root Directory of the project
type GetProjectRootRequest struct {
}

func (m *GetProjectRootRequest) Reset()                    { *m = GetProjectRootRequest{} }
func (m *GetProjectRootRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRootRequest) ProtoMessage()               {}
func (*GetProjectRootRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// / Response of GetProjectRootRequest.
type GetProjectRootResponse struct {
	// / Holds the absolute path of the Project Root directory.
	ProjectRoot string `protobuf:"bytes,1,opt,name=projectRoot" json:"projectRoot,omitempty"`
}

func (m *GetProjectRootResponse) Reset()                    { *m = GetProjectRootResponse{} }
func (m *GetProjectRootResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRootResponse) ProtoMessage()               {}
func (*GetProjectRootResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetProjectRootResponse) GetProjectRoot() string {
	if m != nil {
		return m.ProjectRoot
	}
	return ""
}

// / Request to get the Root Directory of the Gauge installation
type GetInstallationRootRequest struct {
}

func (m *GetInstallationRootRequest) Reset()                    { *m = GetInstallationRootRequest{} }
func (m *GetInstallationRootRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInstallationRootRequest) ProtoMessage()               {}
func (*GetInstallationRootRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// / Response of GetInstallationRootRequest
type GetInstallationRootResponse struct {
	// / Holds the absolute path of the Gauge installation directory
	InstallationRoot string `protobuf:"bytes,1,opt,name=installationRoot" json:"installationRoot,omitempty"`
}

func (m *GetInstallationRootResponse) Reset()                    { *m = GetInstallationRootResponse{} }
func (m *GetInstallationRootResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInstallationRootResponse) ProtoMessage()               {}
func (*GetInstallationRootResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetInstallationRootResponse) GetInstallationRoot() string {
	if m != nil {
		return m.InstallationRoot
	}
	return ""
}

// / Request to get all Steps in the project
type GetAllStepsRequest struct {
}

func (m *GetAllStepsRequest) Reset()                    { *m = GetAllStepsRequest{} }
func (m *GetAllStepsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllStepsRequest) ProtoMessage()               {}
func (*GetAllStepsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// / Response to GetAllStepsRequest
type GetAllStepsResponse struct {
	// / Holds a collection of Steps that are defined in the project.
	AllSteps []*ProtoStepValue `protobuf:"bytes,1,rep,name=allSteps" json:"allSteps,omitempty"`
}

func (m *GetAllStepsResponse) Reset()                    { *m = GetAllStepsResponse{} }
func (m *GetAllStepsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllStepsResponse) ProtoMessage()               {}
func (*GetAllStepsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GetAllStepsResponse) GetAllSteps() []*ProtoStepValue {
	if m != nil {
		return m.AllSteps
	}
	return nil
}

// / Request to get all Specs in the project
type SpecsRequest struct {
	Specs []string `protobuf:"bytes,1,rep,name=specs" json:"specs,omitempty"`
}

func (m *SpecsRequest) Reset()                    { *m = SpecsRequest{} }
func (m *SpecsRequest) String() string            { return proto.CompactTextString(m) }
func (*SpecsRequest) ProtoMessage()               {}
func (*SpecsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *SpecsRequest) GetSpecs() []string {
	if m != nil {
		return m.Specs
	}
	return nil
}

// / Response to GetAllSpecsRequest
type SpecsResponse struct {
	// / Holds a collection of Spec details.
	Details []*SpecsResponse_SpecDetail `protobuf:"bytes,1,rep,name=details" json:"details,omitempty"`
}

func (m *SpecsResponse) Reset()                    { *m = SpecsResponse{} }
func (m *SpecsResponse) String() string            { return proto.CompactTextString(m) }
func (*SpecsResponse) ProtoMessage()               {}
func (*SpecsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *SpecsResponse) GetDetails() []*SpecsResponse_SpecDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type SpecsResponse_SpecDetail struct {
	// / Holds a collection of Specs that are defined in the project.
	Spec *ProtoSpec `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
	// / Holds a collection of parse errors present in the above spec.
	ParseErrors []*Error `protobuf:"bytes,2,rep,name=parseErrors" json:"parseErrors,omitempty"`
}

func (m *SpecsResponse_SpecDetail) Reset()                    { *m = SpecsResponse_SpecDetail{} }
func (m *SpecsResponse_SpecDetail) String() string            { return proto.CompactTextString(m) }
func (*SpecsResponse_SpecDetail) ProtoMessage()               {}
func (*SpecsResponse_SpecDetail) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7, 0} }

func (m *SpecsResponse_SpecDetail) GetSpec() *ProtoSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *SpecsResponse_SpecDetail) GetParseErrors() []*Error {
	if m != nil {
		return m.ParseErrors
	}
	return nil
}

type Error struct {
	// / Holds the filename.
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	// / Holds the line number of the error in file.
	LineNumber int32 `protobuf:"varint,2,opt,name=lineNumber" json:"lineNumber,omitempty"`
	// / Holds the error message.
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *Error) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Error) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// / Request to get all Concepts in the project
type GetAllConceptsRequest struct {
}

func (m *GetAllConceptsRequest) Reset()                    { *m = GetAllConceptsRequest{} }
func (m *GetAllConceptsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllConceptsRequest) ProtoMessage()               {}
func (*GetAllConceptsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

// / Response to GetAllConceptsResponse
type GetAllConceptsResponse struct {
	// / Holds a collection of Concepts that are defined in the project.
	Concepts []*ConceptInfo `protobuf:"bytes,1,rep,name=concepts" json:"concepts,omitempty"`
}

func (m *GetAllConceptsResponse) Reset()                    { *m = GetAllConceptsResponse{} }
func (m *GetAllConceptsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllConceptsResponse) ProtoMessage()               {}
func (*GetAllConceptsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *GetAllConceptsResponse) GetConcepts() []*ConceptInfo {
	if m != nil {
		return m.Concepts
	}
	return nil
}

// / Details of a Concept
type ConceptInfo struct {
	// / The text that defines a concept
	StepValue *ProtoStepValue `protobuf:"bytes,1,opt,name=stepValue" json:"stepValue,omitempty"`
	// / The absolute path to the file that contains the Concept
	Filepath string `protobuf:"bytes,2,opt,name=filepath" json:"filepath,omitempty"`
	// / The line number in the file where the concept is defined.
	LineNumber int32 `protobuf:"varint,3,opt,name=lineNumber" json:"lineNumber,omitempty"`
}

func (m *ConceptInfo) Reset()                    { *m = ConceptInfo{} }
func (m *ConceptInfo) String() string            { return proto.CompactTextString(m) }
func (*ConceptInfo) ProtoMessage()               {}
func (*ConceptInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *ConceptInfo) GetStepValue() *ProtoStepValue {
	if m != nil {
		return m.StepValue
	}
	return nil
}

func (m *ConceptInfo) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *ConceptInfo) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

// / Request to get a Step Value.
type GetStepValueRequest struct {
	// / The text of the Step.
	StepText string `protobuf:"bytes,1,opt,name=stepText" json:"stepText,omitempty"`
	// / Flag to indicate if the Step has an inline table.
	HasInlineTable bool `protobuf:"varint,2,opt,name=hasInlineTable" json:"hasInlineTable,omitempty"`
}

func (m *GetStepValueRequest) Reset()                    { *m = GetStepValueRequest{} }
func (m *GetStepValueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStepValueRequest) ProtoMessage()               {}
func (*GetStepValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *GetStepValueRequest) GetStepText() string {
	if m != nil {
		return m.StepText
	}
	return ""
}

func (m *GetStepValueRequest) GetHasInlineTable() bool {
	if m != nil {
		return m.HasInlineTable
	}
	return false
}

// / Response to GetStepValueRequest
type GetStepValueResponse struct {
	// / The Step corresponding to the request provided.
	StepValue *ProtoStepValue `protobuf:"bytes,1,opt,name=stepValue" json:"stepValue,omitempty"`
}

func (m *GetStepValueResponse) Reset()                    { *m = GetStepValueResponse{} }
func (m *GetStepValueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStepValueResponse) ProtoMessage()               {}
func (*GetStepValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *GetStepValueResponse) GetStepValue() *ProtoStepValue {
	if m != nil {
		return m.StepValue
	}
	return nil
}

// / Request to get the location of language plugin's Lib directory
type GetLanguagePluginLibPathRequest struct {
	// / The language to locate the lib directory for.
	Language string `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
}

func (m *GetLanguagePluginLibPathRequest) Reset()         { *m = GetLanguagePluginLibPathRequest{} }
func (m *GetLanguagePluginLibPathRequest) String() string { return proto.CompactTextString(m) }
func (*GetLanguagePluginLibPathRequest) ProtoMessage()    {}
func (*GetLanguagePluginLibPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{14}
}

func (m *GetLanguagePluginLibPathRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

// / Response to GetLanguagePluginLibPathRequest
type GetLanguagePluginLibPathResponse struct {
	// / Absolute path to the Lib directory of the language.
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *GetLanguagePluginLibPathResponse) Reset()         { *m = GetLanguagePluginLibPathResponse{} }
func (m *GetLanguagePluginLibPathResponse) String() string { return proto.CompactTextString(m) }
func (*GetLanguagePluginLibPathResponse) ProtoMessage()    {}
func (*GetLanguagePluginLibPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{15}
}

func (m *GetLanguagePluginLibPathResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// / A generic failure response
type ErrorResponse struct {
	// / Actual error message
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// / Request to perform a Refactor
type PerformRefactoringRequest struct {
	// / Step to refactor
	OldStep string `protobuf:"bytes,1,opt,name=oldStep" json:"oldStep,omitempty"`
	// / Change to be made
	NewStep string `protobuf:"bytes,2,opt,name=newStep" json:"newStep,omitempty"`
}

func (m *PerformRefactoringRequest) Reset()                    { *m = PerformRefactoringRequest{} }
func (m *PerformRefactoringRequest) String() string            { return proto.CompactTextString(m) }
func (*PerformRefactoringRequest) ProtoMessage()               {}
func (*PerformRefactoringRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *PerformRefactoringRequest) GetOldStep() string {
	if m != nil {
		return m.OldStep
	}
	return ""
}

func (m *PerformRefactoringRequest) GetNewStep() string {
	if m != nil {
		return m.NewStep
	}
	return ""
}

// / Response to PerformRefactoringRequest
type PerformRefactoringResponse struct {
	// / Flag indicating Success
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	// / Error message if the refactoring was unsuccessful.
	Errors []string `protobuf:"bytes,2,rep,name=errors" json:"errors,omitempty"`
	// / Collection of files that were changed as part of the Refactoring.
	FilesChanged []string `protobuf:"bytes,3,rep,name=filesChanged" json:"filesChanged,omitempty"`
}

func (m *PerformRefactoringResponse) Reset()                    { *m = PerformRefactoringResponse{} }
func (m *PerformRefactoringResponse) String() string            { return proto.CompactTextString(m) }
func (*PerformRefactoringResponse) ProtoMessage()               {}
func (*PerformRefactoringResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *PerformRefactoringResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PerformRefactoringResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *PerformRefactoringResponse) GetFilesChanged() []string {
	if m != nil {
		return m.FilesChanged
	}
	return nil
}

// / Request to perform Extract to Concept refactoring
// / The runner does not do the refactoring here, instead it provides inputs enabling the IDE to do refactoring
type ExtractConceptInfoRequest struct {
	// / The text blob containing steps that should be refactored to concept.
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *ExtractConceptInfoRequest) Reset()                    { *m = ExtractConceptInfoRequest{} }
func (m *ExtractConceptInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ExtractConceptInfoRequest) ProtoMessage()               {}
func (*ExtractConceptInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *ExtractConceptInfoRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// / Request to perform Extract to Concept refactoring
type ExtractConceptRequest struct {
	// / The Concept name given by the user
	ConceptName *Step `protobuf:"bytes,1,opt,name=conceptName" json:"conceptName,omitempty"`
	// / steps to extract
	Steps []*Step `protobuf:"bytes,2,rep,name=steps" json:"steps,omitempty"`
	// / Flag indicating if refactoring should be done across project
	ChangeAcrossProject bool `protobuf:"varint,3,opt,name=changeAcrossProject" json:"changeAcrossProject,omitempty"`
	// / The concept filename in which extracted concept will be added
	ConceptFileName string `protobuf:"bytes,4,opt,name=conceptFileName" json:"conceptFileName,omitempty"`
	// / Info related to selected text, only if changeAcrossProject is false
	SelectedTextInfo *TextInfo `protobuf:"bytes,5,opt,name=selectedTextInfo" json:"selectedTextInfo,omitempty"`
}

func (m *ExtractConceptRequest) Reset()                    { *m = ExtractConceptRequest{} }
func (m *ExtractConceptRequest) String() string            { return proto.CompactTextString(m) }
func (*ExtractConceptRequest) ProtoMessage()               {}
func (*ExtractConceptRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *ExtractConceptRequest) GetConceptName() *Step {
	if m != nil {
		return m.ConceptName
	}
	return nil
}

func (m *ExtractConceptRequest) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *ExtractConceptRequest) GetChangeAcrossProject() bool {
	if m != nil {
		return m.ChangeAcrossProject
	}
	return false
}

func (m *ExtractConceptRequest) GetConceptFileName() string {
	if m != nil {
		return m.ConceptFileName
	}
	return ""
}

func (m *ExtractConceptRequest) GetSelectedTextInfo() *TextInfo {
	if m != nil {
		return m.SelectedTextInfo
	}
	return nil
}

type TextInfo struct {
	// / The filename from where concept is being extracted
	FileName string `protobuf:"bytes,1,opt,name=fileName" json:"fileName,omitempty"`
	// / storing the starting and ending line number of selected text
	StartingLineNo int32 `protobuf:"varint,2,opt,name=startingLineNo" json:"startingLineNo,omitempty"`
	EndLineNo      int32 `protobuf:"varint,3,opt,name=endLineNo" json:"endLineNo,omitempty"`
}

func (m *TextInfo) Reset()                    { *m = TextInfo{} }
func (m *TextInfo) String() string            { return proto.CompactTextString(m) }
func (*TextInfo) ProtoMessage()               {}
func (*TextInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *TextInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *TextInfo) GetStartingLineNo() int32 {
	if m != nil {
		return m.StartingLineNo
	}
	return 0
}

func (m *TextInfo) GetEndLineNo() int32 {
	if m != nil {
		return m.EndLineNo
	}
	return 0
}

type Step struct {
	// / name of the step
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// /  table present in step as parameter
	Table string `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	// / name of table in concept heading, if it comes as a param to concept
	ParamTableName string `protobuf:"bytes,3,opt,name=paramTableName" json:"paramTableName,omitempty"`
}

func (m *Step) Reset()                    { *m = Step{} }
func (m *Step) String() string            { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()               {}
func (*Step) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *Step) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Step) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Step) GetParamTableName() string {
	if m != nil {
		return m.ParamTableName
	}
	return ""
}

// / Response to perform Extract to Concept refactoring
type ExtractConceptResponse struct {
	// / Flag indicating Success
	IsSuccess bool `protobuf:"varint,1,opt,name=isSuccess" json:"isSuccess,omitempty"`
	// / Error message if the refactoring was unsuccessful.
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	// / Collection of files that were changed as part of the Refactoring.
	FilesChanged []string `protobuf:"bytes,3,rep,name=filesChanged" json:"filesChanged,omitempty"`
}

func (m *ExtractConceptResponse) Reset()                    { *m = ExtractConceptResponse{} }
func (m *ExtractConceptResponse) String() string            { return proto.CompactTextString(m) }
func (*ExtractConceptResponse) ProtoMessage()               {}
func (*ExtractConceptResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

func (m *ExtractConceptResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *ExtractConceptResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ExtractConceptResponse) GetFilesChanged() []string {
	if m != nil {
		return m.FilesChanged
	}
	return nil
}

// / Request to format spec files
type FormatSpecsRequest struct {
	// / Specs to be formatted
	Specs []string `protobuf:"bytes,1,rep,name=specs" json:"specs,omitempty"`
}

func (m *FormatSpecsRequest) Reset()                    { *m = FormatSpecsRequest{} }
func (m *FormatSpecsRequest) String() string            { return proto.CompactTextString(m) }
func (*FormatSpecsRequest) ProtoMessage()               {}
func (*FormatSpecsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *FormatSpecsRequest) GetSpecs() []string {
	if m != nil {
		return m.Specs
	}
	return nil
}

// / Response on formatting spec files
type FormatSpecsResponse struct {
	// / Errors occurred on formatting
	Errors []string `protobuf:"bytes,1,rep,name=errors" json:"errors,omitempty"`
	// / Warnings occurred on formatting
	Warnings []string `protobuf:"bytes,2,rep,name=warnings" json:"warnings,omitempty"`
}

func (m *FormatSpecsResponse) Reset()                    { *m = FormatSpecsResponse{} }
func (m *FormatSpecsResponse) String() string            { return proto.CompactTextString(m) }
func (*FormatSpecsResponse) ProtoMessage()               {}
func (*FormatSpecsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *FormatSpecsResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *FormatSpecsResponse) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

// / Response when a API message request is not supported.
type UnsupportedApiMessageResponse struct {
}

func (m *UnsupportedApiMessageResponse) Reset()                    { *m = UnsupportedApiMessageResponse{} }
func (m *UnsupportedApiMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*UnsupportedApiMessageResponse) ProtoMessage()               {}
func (*UnsupportedApiMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

// / A generic message composing of all possible operations.
// / One of the Request/Response fields will have value, depending on the MessageType set.
type APIMessage struct {
	// / Type of API call being made
	MessageType APIMessage_APIMessageType `protobuf:"varint,1,opt,name=messageType,enum=gauge.messages.APIMessage_APIMessageType" json:"messageType,omitempty"`
	// / A unique id to represent this message. A response to the message should copy over this value.
	// / This is used to synchronize messages & responses
	MessageId int64 `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
	// / [GetProjectRootRequest](#gauge.messages.GetProjectRootRequest)
	ProjectRootRequest *GetProjectRootRequest `protobuf:"bytes,3,opt,name=projectRootRequest" json:"projectRootRequest,omitempty"`
	// / [GetProjectRootResponse](#gauge.messages.GetProjectRootResponse)
	ProjectRootResponse *GetProjectRootResponse `protobuf:"bytes,4,opt,name=projectRootResponse" json:"projectRootResponse,omitempty"`
	// / [GetInstallationRootRequest](#gauge.messages.GetInstallationRootRequest)
	InstallationRootRequest *GetInstallationRootRequest `protobuf:"bytes,5,opt,name=installationRootRequest" json:"installationRootRequest,omitempty"`
	// / [GetInstallationRootResponse](#gauge.messages.GetInstallationRootResponse)
	InstallationRootResponse *GetInstallationRootResponse `protobuf:"bytes,6,opt,name=installationRootResponse" json:"installationRootResponse,omitempty"`
	// / [GetAllStepsRequest](#gauge.messages.GetAllStepsRequest)
	AllStepsRequest *GetAllStepsRequest `protobuf:"bytes,7,opt,name=allStepsRequest" json:"allStepsRequest,omitempty"`
	// / [GetAllStepsResponse](#gauge.messages.GetAllStepsResponse)
	AllStepsResponse *GetAllStepsResponse `protobuf:"bytes,8,opt,name=allStepsResponse" json:"allStepsResponse,omitempty"`
	// / [GetAllSpecsRequest](#gauge.messages.GetAllSpecsRequest)
	SpecsRequest *SpecsRequest `protobuf:"bytes,9,opt,name=specsRequest" json:"specsRequest,omitempty"`
	// / [GetAllSpecsResponse](#gauge.messages.GetAllSpecsResponse)
	SpecsResponse *SpecsResponse `protobuf:"bytes,10,opt,name=specsResponse" json:"specsResponse,omitempty"`
	// / [GetStepValueRequest](#gauge.messages.GetStepValueRequest)
	StepValueRequest *GetStepValueRequest `protobuf:"bytes,11,opt,name=stepValueRequest" json:"stepValueRequest,omitempty"`
	// / [GetStepValueResponse](#gauge.messages.GetStepValueResponse)
	StepValueResponse *GetStepValueResponse `protobuf:"bytes,12,opt,name=stepValueResponse" json:"stepValueResponse,omitempty"`
	// / [GetLanguagePluginLibPathRequest](#gauge.messages.GetLanguagePluginLibPathRequest)
	LibPathRequest *GetLanguagePluginLibPathRequest `protobuf:"bytes,13,opt,name=libPathRequest" json:"libPathRequest,omitempty"`
	// / [GetLanguagePluginLibPathResponse](#gauge.messages.GetLanguagePluginLibPathResponse)
	LibPathResponse *GetLanguagePluginLibPathResponse `protobuf:"bytes,14,opt,name=libPathResponse" json:"libPathResponse,omitempty"`
	// / [ErrorResponse](#gauge.messages.ErrorResponse)
	Error *ErrorResponse `protobuf:"bytes,15,opt,name=error" json:"error,omitempty"`
	// / [GetAllConceptsRequest](#gauge.messages.GetAllConceptsRequest)
	AllConceptsRequest *GetAllConceptsRequest `protobuf:"bytes,16,opt,name=allConceptsRequest" json:"allConceptsRequest,omitempty"`
	// / [GetAllConceptsResponse](#gauge.messages.GetAllConceptsResponse)
	AllConceptsResponse *GetAllConceptsResponse `protobuf:"bytes,17,opt,name=allConceptsResponse" json:"allConceptsResponse,omitempty"`
	// / [PerformRefactoringRequest](#gauge.messages.PerformRefactoringRequest)
	PerformRefactoringRequest *PerformRefactoringRequest `protobuf:"bytes,18,opt,name=performRefactoringRequest" json:"performRefactoringRequest,omitempty"`
	// / [PerformRefactoringResponse](#gauge.messages.PerformRefactoringResponse)
	PerformRefactoringResponse *PerformRefactoringResponse `protobuf:"bytes,19,opt,name=performRefactoringResponse" json:"performRefactoringResponse,omitempty"`
	// / [ExtractConceptRequest](#gauge.messages.ExtractConceptRequest)
	ExtractConceptRequest *ExtractConceptRequest `protobuf:"bytes,20,opt,name=extractConceptRequest" json:"extractConceptRequest,omitempty"`
	// / [ExtractConceptResponse](#gauge.messages.ExtractConceptResponse)
	ExtractConceptResponse *ExtractConceptResponse `protobuf:"bytes,21,opt,name=extractConceptResponse" json:"extractConceptResponse,omitempty"`
	// / [FormatSpecsRequest] (#gauge.messages.FormatSpecsRequest)
	FormatSpecsRequest *FormatSpecsRequest `protobuf:"bytes,22,opt,name=formatSpecsRequest" json:"formatSpecsRequest,omitempty"`
	// / [FormatSpecsResponse] (#gauge.messages.FormatSpecsResponse)
	FormatSpecsResponse *FormatSpecsResponse `protobuf:"bytes,23,opt,name=formatSpecsResponse" json:"formatSpecsResponse,omitempty"`
	// / [UnsupportedApiMessageResponse] (#gauge.messages.UnsupportedApiMessageResponse)
	UnsupportedApiMessageResponse *UnsupportedApiMessageResponse `protobuf:"bytes,24,opt,name=unsupportedApiMessageResponse" json:"unsupportedApiMessageResponse,omitempty"`
}

func (m *APIMessage) Reset()                    { *m = APIMessage{} }
func (m *APIMessage) String() string            { return proto.CompactTextString(m) }
func (*APIMessage) ProtoMessage()               {}
func (*APIMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *APIMessage) GetMessageType() APIMessage_APIMessageType {
	if m != nil {
		return m.MessageType
	}
	return APIMessage_GetProjectRootRequest
}

func (m *APIMessage) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *APIMessage) GetProjectRootRequest() *GetProjectRootRequest {
	if m != nil {
		return m.ProjectRootRequest
	}
	return nil
}

func (m *APIMessage) GetProjectRootResponse() *GetProjectRootResponse {
	if m != nil {
		return m.ProjectRootResponse
	}
	return nil
}

func (m *APIMessage) GetInstallationRootRequest() *GetInstallationRootRequest {
	if m != nil {
		return m.InstallationRootRequest
	}
	return nil
}

func (m *APIMessage) GetInstallationRootResponse() *GetInstallationRootResponse {
	if m != nil {
		return m.InstallationRootResponse
	}
	return nil
}

func (m *APIMessage) GetAllStepsRequest() *GetAllStepsRequest {
	if m != nil {
		return m.AllStepsRequest
	}
	return nil
}

func (m *APIMessage) GetAllStepsResponse() *GetAllStepsResponse {
	if m != nil {
		return m.AllStepsResponse
	}
	return nil
}

func (m *APIMessage) GetSpecsRequest() *SpecsRequest {
	if m != nil {
		return m.SpecsRequest
	}
	return nil
}

func (m *APIMessage) GetSpecsResponse() *SpecsResponse {
	if m != nil {
		return m.SpecsResponse
	}
	return nil
}

func (m *APIMessage) GetStepValueRequest() *GetStepValueRequest {
	if m != nil {
		return m.StepValueRequest
	}
	return nil
}

func (m *APIMessage) GetStepValueResponse() *GetStepValueResponse {
	if m != nil {
		return m.StepValueResponse
	}
	return nil
}

func (m *APIMessage) GetLibPathRequest() *GetLanguagePluginLibPathRequest {
	if m != nil {
		return m.LibPathRequest
	}
	return nil
}

func (m *APIMessage) GetLibPathResponse() *GetLanguagePluginLibPathResponse {
	if m != nil {
		return m.LibPathResponse
	}
	return nil
}

func (m *APIMessage) GetError() *ErrorResponse {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *APIMessage) GetAllConceptsRequest() *GetAllConceptsRequest {
	if m != nil {
		return m.AllConceptsRequest
	}
	return nil
}

func (m *APIMessage) GetAllConceptsResponse() *GetAllConceptsResponse {
	if m != nil {
		return m.AllConceptsResponse
	}
	return nil
}

func (m *APIMessage) GetPerformRefactoringRequest() *PerformRefactoringRequest {
	if m != nil {
		return m.PerformRefactoringRequest
	}
	return nil
}

func (m *APIMessage) GetPerformRefactoringResponse() *PerformRefactoringResponse {
	if m != nil {
		return m.PerformRefactoringResponse
	}
	return nil
}

func (m *APIMessage) GetExtractConceptRequest() *ExtractConceptRequest {
	if m != nil {
		return m.ExtractConceptRequest
	}
	return nil
}

func (m *APIMessage) GetExtractConceptResponse() *ExtractConceptResponse {
	if m != nil {
		return m.ExtractConceptResponse
	}
	return nil
}

func (m *APIMessage) GetFormatSpecsRequest() *FormatSpecsRequest {
	if m != nil {
		return m.FormatSpecsRequest
	}
	return nil
}

func (m *APIMessage) GetFormatSpecsResponse() *FormatSpecsResponse {
	if m != nil {
		return m.FormatSpecsResponse
	}
	return nil
}

func (m *APIMessage) GetUnsupportedApiMessageResponse() *UnsupportedApiMessageResponse {
	if m != nil {
		return m.UnsupportedApiMessageResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProjectRootRequest)(nil), "gauge.messages.GetProjectRootRequest")
	proto.RegisterType((*GetProjectRootResponse)(nil), "gauge.messages.GetProjectRootResponse")
	proto.RegisterType((*GetInstallationRootRequest)(nil), "gauge.messages.GetInstallationRootRequest")
	proto.RegisterType((*GetInstallationRootResponse)(nil), "gauge.messages.GetInstallationRootResponse")
	proto.RegisterType((*GetAllStepsRequest)(nil), "gauge.messages.GetAllStepsRequest")
	proto.RegisterType((*GetAllStepsResponse)(nil), "gauge.messages.GetAllStepsResponse")
	proto.RegisterType((*SpecsRequest)(nil), "gauge.messages.SpecsRequest")
	proto.RegisterType((*SpecsResponse)(nil), "gauge.messages.SpecsResponse")
	proto.RegisterType((*SpecsResponse_SpecDetail)(nil), "gauge.messages.SpecsResponse.SpecDetail")
	proto.RegisterType((*Error)(nil), "gauge.messages.Error")
	proto.RegisterType((*GetAllConceptsRequest)(nil), "gauge.messages.GetAllConceptsRequest")
	proto.RegisterType((*GetAllConceptsResponse)(nil), "gauge.messages.GetAllConceptsResponse")
	proto.RegisterType((*ConceptInfo)(nil), "gauge.messages.ConceptInfo")
	proto.RegisterType((*GetStepValueRequest)(nil), "gauge.messages.GetStepValueRequest")
	proto.RegisterType((*GetStepValueResponse)(nil), "gauge.messages.GetStepValueResponse")
	proto.RegisterType((*GetLanguagePluginLibPathRequest)(nil), "gauge.messages.GetLanguagePluginLibPathRequest")
	proto.RegisterType((*GetLanguagePluginLibPathResponse)(nil), "gauge.messages.GetLanguagePluginLibPathResponse")
	proto.RegisterType((*ErrorResponse)(nil), "gauge.messages.ErrorResponse")
	proto.RegisterType((*PerformRefactoringRequest)(nil), "gauge.messages.PerformRefactoringRequest")
	proto.RegisterType((*PerformRefactoringResponse)(nil), "gauge.messages.PerformRefactoringResponse")
	proto.RegisterType((*ExtractConceptInfoRequest)(nil), "gauge.messages.ExtractConceptInfoRequest")
	proto.RegisterType((*ExtractConceptRequest)(nil), "gauge.messages.ExtractConceptRequest")
	proto.RegisterType((*TextInfo)(nil), "gauge.messages.textInfo")
	proto.RegisterType((*Step)(nil), "gauge.messages.step")
	proto.RegisterType((*ExtractConceptResponse)(nil), "gauge.messages.ExtractConceptResponse")
	proto.RegisterType((*FormatSpecsRequest)(nil), "gauge.messages.FormatSpecsRequest")
	proto.RegisterType((*FormatSpecsResponse)(nil), "gauge.messages.FormatSpecsResponse")
	proto.RegisterType((*UnsupportedApiMessageResponse)(nil), "gauge.messages.UnsupportedApiMessageResponse")
	proto.RegisterType((*APIMessage)(nil), "gauge.messages.APIMessage")
	proto.RegisterEnum("gauge.messages.APIMessage_APIMessageType", APIMessage_APIMessageType_name, APIMessage_APIMessageType_value)
}

func init() { proto.RegisterFile("api.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x58, 0xeb, 0x6e, 0xdc, 0xb6,
	0x12, 0x3e, 0xeb, 0xeb, 0xee, 0xac, 0xbd, 0xa6, 0xb9, 0x5e, 0x9b, 0x76, 0xe2, 0x24, 0x87, 0xb9,
	0xc0, 0x27, 0x07, 0x71, 0x02, 0x07, 0x48, 0x80, 0xe0, 0x1c, 0xa0, 0xce, 0x15, 0x8b, 0xba, 0x89,
	0xcb, 0x38, 0x6d, 0xda, 0xa2, 0x05, 0xe4, 0x5d, 0x7a, 0xa3, 0x40, 0x96, 0x54, 0x51, 0x8b, 0xa4,
	0x3f, 0xfb, 0xab, 0x4f, 0xd1, 0x17, 0xe8, 0x9b, 0xf4, 0x69, 0xfa, 0x0a, 0x25, 0x29, 0x6a, 0x57,
	0xa2, 0xa8, 0xb5, 0x81, 0xfe, 0x13, 0x87, 0x33, 0xdf, 0x0c, 0xe7, 0xc6, 0x11, 0xa1, 0xe5, 0xc5,
	0xfe, 0x7e, 0x9c, 0x44, 0x69, 0x84, 0x3b, 0x23, 0x6f, 0x3c, 0xe2, 0xfb, 0xe7, 0x5c, 0x08, 0x6f,
	0xc4, 0xc5, 0x0e, 0x88, 0x98, 0x0f, 0xb2, 0x3d, 0xba, 0x05, 0xbd, 0x57, 0x3c, 0x3d, 0x4e, 0xa2,
	0x8f, 0x7c, 0x90, 0xb2, 0x28, 0x4a, 0x19, 0xff, 0x79, 0xcc, 0x45, 0x4a, 0x9f, 0xc0, 0xa6, 0xbd,
	0x21, 0xe2, 0x28, 0x14, 0x1c, 0xdf, 0x80, 0x76, 0x3c, 0x25, 0x93, 0xc6, 0x8d, 0xc6, 0x5e, 0x8b,
	0x15, 0x49, 0xf4, 0x2a, 0xec, 0x48, 0xd9, 0x7e, 0x28, 0x52, 0x2f, 0x08, 0xbc, 0xd4, 0x8f, 0xc2,
	0x22, 0x72, 0x1f, 0xae, 0x38, 0x77, 0x0d, 0xfc, 0x5d, 0x40, 0xbe, 0xb5, 0x67, 0x74, 0x54, 0xe8,
	0x74, 0x03, 0xb0, 0x84, 0x3a, 0x0c, 0x82, 0xb7, 0x29, 0x8f, 0x45, 0xae, 0xe0, 0x6b, 0xe8, 0x96,
	0xa8, 0x06, 0xf8, 0x09, 0x34, 0x3d, 0x43, 0x93, 0x80, 0xf3, 0x7b, 0xed, 0x83, 0x6b, 0xfb, 0x65,
	0xcf, 0xec, 0x1f, 0x2b, 0x9f, 0x28, 0x8e, 0x6f, 0xbc, 0x60, 0xcc, 0xd9, 0x84, 0x9f, 0xde, 0x82,
	0x95, 0xb7, 0xd2, 0x69, 0xb9, 0x0a, 0xbc, 0x01, 0x8b, 0xca, 0x89, 0x19, 0x50, 0x8b, 0x65, 0x0b,
	0xfa, 0x67, 0x03, 0x56, 0x0d, 0x9b, 0xd1, 0xf9, 0x14, 0x96, 0x87, 0x3c, 0xf5, 0xfc, 0x20, 0x57,
	0xb9, 0x67, 0xab, 0x2c, 0xf1, 0xeb, 0xd5, 0x73, 0x2d, 0xc0, 0x72, 0xc1, 0x9d, 0x14, 0x60, 0x4a,
	0xc6, 0xf7, 0x60, 0x41, 0x29, 0xd3, 0x2e, 0x69, 0x1f, 0x6c, 0xbb, 0x4f, 0x20, 0x19, 0x98, 0x66,
	0xc3, 0x8f, 0x65, 0xb0, 0xbc, 0x44, 0xf0, 0x17, 0x49, 0x12, 0x25, 0x82, 0xcc, 0x69, 0x23, 0x7a,
	0xb6, 0x94, 0xde, 0x65, 0x45, 0x4e, 0xfa, 0x23, 0x2c, 0xea, 0x2f, 0xbc, 0x03, 0xcd, 0x33, 0x3f,
	0xe0, 0xa1, 0x77, 0xce, 0x4d, 0x1c, 0x26, 0x6b, 0x7c, 0x0d, 0x20, 0xf0, 0x43, 0xfe, 0x7a, 0x7c,
	0x7e, 0xca, 0x13, 0x09, 0xde, 0xd8, 0x5b, 0x64, 0x05, 0x0a, 0x26, 0xb0, 0x6c, 0x74, 0x90, 0x79,
	0x2d, 0x9a, 0x2f, 0x4d, 0xde, 0xc9, 0x18, 0x3d, 0x8b, 0xc2, 0x01, 0x8f, 0xd3, 0x42, 0xf0, 0x36,
	0xed, 0x0d, 0xe3, 0xcb, 0xc7, 0xd0, 0x1c, 0x18, 0x9a, 0x71, 0xe6, 0x15, 0xfb, 0x1c, 0x46, 0xa6,
	0x1f, 0x9e, 0x45, 0x6c, 0xc2, 0x4c, 0x7f, 0x6b, 0x40, 0xbb, 0xb0, 0x83, 0xff, 0x07, 0x2d, 0x91,
	0xc7, 0xd8, 0xf8, 0xf1, 0xa2, 0x4c, 0x98, 0x0a, 0xe4, 0xfe, 0x88, 0xbd, 0xf4, 0x83, 0x3e, 0xb1,
	0xf1, 0x87, 0x5a, 0x5b, 0xfe, 0x98, 0xb7, 0xfd, 0x41, 0xbf, 0xd3, 0x99, 0x39, 0x85, 0x35, 0xd9,
	0x24, 0x21, 0x15, 0xfe, 0x09, 0xff, 0x9c, 0xa7, 0xfa, 0x64, 0x8d, 0xef, 0x40, 0xe7, 0x83, 0x27,
	0xfa, 0xa1, 0x42, 0x39, 0xf1, 0x4e, 0x03, 0xae, 0x95, 0x36, 0x99, 0x45, 0xa5, 0x27, 0xb0, 0x51,
	0x86, 0x36, 0x5e, 0xfb, 0x47, 0x87, 0xa5, 0xff, 0x87, 0xeb, 0x12, 0xf5, 0xc8, 0x0b, 0x47, 0x63,
	0xc9, 0x79, 0x1c, 0x8c, 0x47, 0x7e, 0x78, 0xe4, 0x9f, 0x1e, 0xcb, 0xc3, 0x16, 0x8c, 0x0f, 0xcc,
	0x7e, 0x6e, 0x7c, 0xbe, 0xa6, 0x8f, 0xe0, 0x46, 0xbd, 0xb8, 0x31, 0x10, 0xc3, 0x82, 0xf6, 0x65,
	0x26, 0xab, 0xbf, 0xe9, 0x6d, 0x58, 0xcd, 0x52, 0x32, 0x67, 0x92, 0xf5, 0xc6, 0x15, 0xc1, 0x70,
	0x65, 0x0b, 0xfa, 0x06, 0xb6, 0x8f, 0x79, 0x72, 0x16, 0x25, 0xe7, 0x8c, 0x9f, 0x79, 0x83, 0x34,
	0x4a, 0xfc, 0x70, 0x94, 0xdb, 0x25, 0x73, 0x2f, 0x0a, 0x86, 0xea, 0x54, 0x46, 0x28, 0x5f, 0xaa,
	0x9d, 0x90, 0x7f, 0xd2, 0x3b, 0x59, 0x00, 0xf3, 0x25, 0x4d, 0x60, 0xc7, 0x05, 0x68, 0x8c, 0x90,
	0x72, 0x62, 0x3c, 0x18, 0x48, 0xaf, 0x69, 0xc4, 0x26, 0xcb, 0x97, 0x78, 0x13, 0x96, 0xf8, 0xb4,
	0xc0, 0x5a, 0xcc, 0xac, 0x30, 0x85, 0x15, 0x95, 0x1b, 0xe2, 0xd9, 0x07, 0xe9, 0x02, 0x3e, 0x94,
	0x19, 0xa1, 0x76, 0x4b, 0x34, 0x7a, 0x1f, 0xb6, 0x5f, 0x7c, 0x4e, 0x13, 0xa9, 0xad, 0x98, 0xbd,
	0xe6, 0x10, 0xd2, 0x39, 0xe9, 0x34, 0x2b, 0xf4, 0x37, 0xfd, 0x7d, 0x0e, 0x7a, 0x65, 0x89, 0x9c,
	0xfb, 0x11, 0xb4, 0x4d, 0xd2, 0xbf, 0xce, 0xab, 0xb5, 0x7d, 0xb0, 0x61, 0x47, 0x5b, 0x45, 0x97,
	0x15, 0x19, 0x65, 0xcb, 0x5d, 0x14, 0xba, 0x2d, 0x66, 0xed, 0xc1, 0x2d, 0x91, 0xb1, 0xe0, 0x07,
	0xd0, 0x1d, 0x68, 0xcb, 0x0f, 0x07, 0x49, 0x24, 0x84, 0xb9, 0x20, 0x74, 0xae, 0x37, 0x99, 0x6b,
	0x0b, 0xef, 0xc1, 0x9a, 0x51, 0xf6, 0x52, 0x9e, 0x5b, 0x5b, 0xb6, 0xa0, 0x8f, 0x63, 0x93, 0xf1,
	0x73, 0x40, 0x82, 0x07, 0x52, 0x86, 0x0f, 0x55, 0xee, 0x2b, 0x47, 0x90, 0x45, 0x7d, 0x08, 0x62,
	0x9b, 0x94, 0x9a, 0x7d, 0x56, 0x91, 0xa0, 0x01, 0x34, 0xf3, 0xdd, 0xbc, 0x58, 0x5f, 0x5b, 0xcd,
	0x4b, 0x6b, 0x93, 0x95, 0x25, 0xaf, 0x93, 0x24, 0x95, 0x21, 0x3e, 0x52, 0x25, 0x1a, 0x99, 0x06,
	0x66, 0x51, 0xf1, 0x55, 0x68, 0xf1, 0x70, 0x68, 0x58, 0xb2, 0x9a, 0x9e, 0x12, 0xe8, 0x7b, 0xd9,
	0x8f, 0x55, 0x52, 0xc9, 0x48, 0x15, 0x5a, 0xa4, 0xfe, 0x56, 0x59, 0x9b, 0x4e, 0x4a, 0x56, 0x66,
	0xad, 0x5e, 0x28, 0xbd, 0xb2, 0xd1, 0x7a, 0xe7, 0xba, 0x6e, 0xb5, 0x65, 0x59, 0x6f, 0xb4, 0xa8,
	0x34, 0x86, 0x4d, 0x3b, 0xcc, 0x26, 0x11, 0xa5, 0x45, 0xbe, 0x78, 0x5b, 0x4a, 0xc5, 0x29, 0x61,
	0x5a, 0x2b, 0x73, 0x85, 0x5a, 0xb9, 0x54, 0x2a, 0xde, 0x05, 0xfc, 0x52, 0xe6, 0xbe, 0x97, 0x5e,
	0xe2, 0xae, 0xeb, 0x43, 0xb7, 0xc4, 0x6b, 0x4c, 0x9b, 0x56, 0x42, 0xa3, 0x54, 0x09, 0x32, 0x10,
	0x9f, 0xbc, 0x24, 0x94, 0x5e, 0xcd, 0x6b, 0x64, 0xb2, 0xa6, 0xd7, 0x61, 0xf7, 0x5d, 0x28, 0xc6,
	0x71, 0x1c, 0x25, 0x32, 0x8e, 0x87, 0xb1, 0xff, 0x55, 0x16, 0xe5, 0x1c, 0x94, 0xfe, 0xda, 0x03,
	0x38, 0x3c, 0xee, 0x1b, 0x32, 0xfe, 0x12, 0xda, 0x26, 0x0f, 0x4e, 0x7e, 0x89, 0x33, 0x8f, 0x77,
	0x0e, 0xfe, 0x63, 0x67, 0xc8, 0x54, 0xa0, 0xf0, 0xa9, 0x04, 0x58, 0x51, 0x5a, 0xf9, 0xd2, 0x2c,
	0xfb, 0x43, 0xed, 0xb1, 0x79, 0x36, 0x25, 0xe0, 0x77, 0x80, 0xe3, 0xca, 0x6c, 0xa4, 0xe3, 0xd5,
	0x3e, 0xb8, 0x6d, 0x6b, 0x74, 0x0e, 0x52, 0xcc, 0x01, 0x80, 0xdf, 0x43, 0x37, 0xae, 0x4e, 0x56,
	0xba, 0x2c, 0xda, 0x07, 0x77, 0x2e, 0xc2, 0xcd, 0xb8, 0x99, 0x0b, 0x02, 0x0f, 0x61, 0xcb, 0x77,
	0xcf, 0x5d, 0xa6, 0x92, 0xee, 0x3a, 0xd0, 0x6b, 0x26, 0x35, 0x56, 0x07, 0x85, 0x47, 0x40, 0xfc,
	0x9a, 0xf9, 0x8d, 0x2c, 0x69, 0x35, 0xff, 0xbd, 0x94, 0x1a, 0x73, 0x92, 0x5a, 0x30, 0x7c, 0x04,
	0x6b, 0x5e, 0x79, 0xba, 0x23, 0xcb, 0x1a, 0x9f, 0x3a, 0xf0, 0xad, 0x39, 0x90, 0xd9, 0xa2, 0xf8,
	0x0d, 0x20, 0xcf, 0x9a, 0x0a, 0x49, 0x53, 0xc3, 0xdd, 0x9c, 0x09, 0x67, 0xcc, 0xac, 0x08, 0xe3,
	0x2f, 0x60, 0x45, 0x14, 0x4a, 0x85, 0xb4, 0x34, 0xd8, 0xd5, 0x9a, 0x19, 0x2f, 0xb3, 0xaa, 0x24,
	0x81, 0x9f, 0xc1, 0xaa, 0x28, 0x16, 0x10, 0x01, 0x0d, 0xb1, 0x3b, 0x73, 0x4c, 0x64, 0x65, 0x19,
	0x75, 0x2e, 0x61, 0xcd, 0x14, 0xa4, 0x5d, 0x7b, 0x2e, 0x7b, 0xfc, 0x60, 0x15, 0x61, 0xcc, 0x60,
	0x5d, 0xd8, 0x93, 0x04, 0x59, 0xd1, 0x88, 0xb7, 0x66, 0x23, 0x1a, 0x03, 0xab, 0xe2, 0xf8, 0x5b,
	0xe8, 0x04, 0xa5, 0xc9, 0x81, 0xac, 0x6a, 0xc0, 0xfb, 0x0e, 0xc0, 0x59, 0x03, 0x07, 0xb3, 0x60,
	0xf0, 0xf7, 0xb0, 0x16, 0x94, 0x67, 0x0a, 0xd2, 0xd1, 0xc8, 0x0f, 0x2e, 0x8f, 0x6c, 0xcc, 0xb6,
	0x81, 0xf0, 0xc3, 0xbc, 0x97, 0xae, 0xb9, 0xc3, 0x52, 0x9a, 0x52, 0xf2, 0x56, 0x2b, 0x9b, 0x86,
	0x57, 0x19, 0x6c, 0x09, 0xaa, 0x6d, 0x1a, 0xd5, 0x29, 0x98, 0x39, 0x00, 0x54, 0xd3, 0xf0, 0xaa,
	0x63, 0x31, 0x59, 0xaf, 0x6d, 0x1a, 0x8e, 0x21, 0x9a, 0xb9, 0x20, 0x64, 0x39, 0x6f, 0xc7, 0x75,
	0x73, 0x14, 0xc1, 0x1a, 0xbf, 0xd2, 0x5e, 0x6b, 0x07, 0x2f, 0x56, 0x8f, 0x85, 0x3f, 0xc2, 0x4e,
	0x5c, 0x3b, 0x5f, 0x91, 0xae, 0xbb, 0x41, 0xd5, 0x4f, 0x64, 0x6c, 0x06, 0x1a, 0xfe, 0x01, 0x7a,
	0xdc, 0x35, 0x25, 0x91, 0x0d, 0x77, 0x20, 0x9c, 0x23, 0x15, 0x73, 0x63, 0xe0, 0x9f, 0x60, 0x93,
	0x3b, 0xef, 0x66, 0xd2, 0x73, 0x87, 0xc3, 0x7d, 0x93, 0xb3, 0x1a, 0x14, 0x59, 0x80, 0xf8, 0xac,
	0x72, 0x13, 0x93, 0x4d, 0x77, 0xeb, 0xab, 0xde, 0xd9, 0xcc, 0x21, 0x2d, 0xd3, 0xb2, 0x7b, 0x56,
	0xbd, 0xb1, 0xc9, 0x96, 0xbb, 0x51, 0x38, 0x2e, 0x77, 0xe6, 0x92, 0xc7, 0x02, 0x76, 0xc7, 0xb3,
	0x6e, 0x6f, 0x42, 0xb4, 0x82, 0x7b, 0xb6, 0x82, 0x99, 0x57, 0x3e, 0x9b, 0x8d, 0x49, 0xff, 0x5a,
	0x80, 0x4e, 0xf9, 0x56, 0xc7, 0xdb, 0x35, 0x2f, 0x19, 0xe8, 0x5f, 0x72, 0xf8, 0xa8, 0x79, 0xcb,
	0x40, 0x0d, 0xf9, 0xcb, 0x36, 0xe3, 0xad, 0x02, 0xcd, 0xe1, 0xeb, 0x33, 0x5f, 0x2b, 0xd0, 0xbc,
	0x9c, 0x78, 0x1c, 0x6f, 0x10, 0x68, 0xa1, 0x4c, 0x9f, 0xf0, 0x2f, 0x62, 0x54, 0x7e, 0x4a, 0x40,
	0x4b, 0x78, 0xdd, 0x7a, 0x35, 0x40, 0xcb, 0x78, 0xcb, 0xf9, 0xa3, 0x88, 0x9a, 0xf2, 0x1f, 0xc4,
	0xf9, 0x9b, 0x87, 0x5a, 0xf8, 0xe6, 0x85, 0xbf, 0x6a, 0x08, 0xf0, 0xad, 0x8b, 0x7f, 0xc8, 0x50,
	0x5b, 0x19, 0x54, 0x6a, 0x6c, 0x68, 0xc5, 0x78, 0xb7, 0xda, 0xa9, 0xd0, 0xaa, 0xf1, 0xae, 0xa3,
	0xd9, 0xa0, 0x0e, 0xde, 0x9d, 0xf1, 0x87, 0x86, 0xd6, 0x94, 0xf3, 0xeb, 0xab, 0x1b, 0x21, 0xa5,
	0xd5, 0x59, 0x96, 0x68, 0x5d, 0x69, 0x75, 0xd7, 0x14, 0xc2, 0xca, 0xf5, 0xd5, 0x9a, 0x40, 0x5d,
	0xe5, 0x55, 0x47, 0x5a, 0xa3, 0x0d, 0xfc, 0xef, 0x0b, 0x26, 0x50, 0xd4, 0x7b, 0xba, 0xfe, 0xc7,
	0x5c, 0xe7, 0x95, 0xce, 0x60, 0xb3, 0x27, 0x4e, 0x97, 0xf4, 0x13, 0xda, 0xc3, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x7c, 0x30, 0x3f, 0x65, 0x6b, 0x13, 0x00, 0x00,
}
