name: Release on PR Merge

on: deployment

jobs:
  release:
    if: github.event.deployment.environment == 'production'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GAUGEBOT_GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build artifacts
        run: |
          go run build/make.go --all-platforms
          go run build/make.go --all-platforms --distro

      - name: Release on github
        run: |
          if [ -z "$version" ]; then
            version=$(cd bin/distros && ls spectacle* | head -1 | sed "s/\.[^\.]*$//" | sed "s/spectacle-//" | sed | sed "s/-[a-z]*\.[a-z0-9_]*$//");
          fi
          echo "VERSION=$version" >> $GITHUB_ENV

          echo "---------------------------"
          echo "Updating release v$version"
          echo "---------------------------"
          echo -e "Spectacle v$version\n\n" > desc.txt
          release_description=$(ruby -e "$(curl -sSfL https://github.com/getgauge/gauge/raw/master/build/create_release_text.rb)" getgauge spectacle)
          echo "$release_description" >> desc.txt
          gh release create --title "Spectacle v${version}" --notes-file ./desc.txt "v${version}" bin/distros/*

      - name: Update metadata in gauge-repository
        run: |
          git clone https://github.com/getgauge/gauge-repository.git
          cd gauge-repository
          python update_metadata.py spectacle $VERSION
          commit_message=$(echo -e "Update spectacle to v$VERSION")
          git commit -am "$commit_message"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/getgauge/gauge-repository.git" master